export const actionTypes = {
  LOAD_USER_LIST: 'LOAD_USER_LIST',
  LOAD_USER_LIST_SUCCESS: 'LOAD_USER_LIST_SUCCESS',
  LOAD_USER_LIST_FAIL: 'LOAD_USER_LIST_FAIL',

  LOAD_USER: 'LOAD_USER',
  LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
  LOAD_USER_FAIL: 'LOAD_USER_FAIL',

  SAVE_USER: 'SAVE_USER',
  SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
  SAVE_USER_FAIL: 'SAVE_USER_FAIL',

  CLEAR_SELECTED_USER: 'CLEAR_SELECTED_USER'
};
